# Generated by Django 5.1.4 on 2025-01-24 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_agency_name_user_profile_completed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='activity_areas',
            field=models.JSONField(blank=True, null=True, verbose_name='محله\u200cهای حوزه فعالیت'),
        ),
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='آدرس کامل'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='/images/logo/logo@2x.png', upload_to='avatars/', verbose_name='آواتار'),
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='توضیحات'),
        ),
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='نام و نام خانوادگی'),
        ),
        migrations.AddField(
            model_name='user',
            name='specialization',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='تخصص مشاور'),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp_number',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره واتساپ'),
        ),
    ]
