# Generated by Django 5.1.4 on 2025-01-24 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_activity_areas_user_address_user_avatar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=models.ImageField(default='/images/logo/images.png', upload_to='avatars/', verbose_name='آواتار'),
        ),
    ]
