# Generated by Django 5.1.4 on 2025-01-24 19:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان آگهی')),
                ('property_type', models.CharField(choices=[('apartment', 'آپارتمان'), ('villa', 'ویلا'), ('land', 'زمین'), ('house', 'خانه')], max_length=20, verbose_name='نوع ملک')),
                ('ad_type', models.CharField(choices=[('sale', 'فروش'), ('rent', 'رهن و اجاره'), ('purchase', 'خرید'), ('lease', 'اجاره')], max_length=20, verbose_name='نوع آگهی')),
                ('price_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='قیمت حداقل')),
                ('price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='قیمت حداکثر')),
                ('deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='پول پیش')),
                ('rent', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='اجاره ماهیانه')),
                ('city', models.CharField(max_length=50, verbose_name='شهر')),
                ('postalcode', models.CharField(max_length=10, verbose_name='کد پستی')),
                ('location', models.CharField(max_length=255, verbose_name='آدرس کامل')),
                ('images', models.ImageField(blank=True, null=True, upload_to='ads/', verbose_name='تصاویر آگهی')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='متراژ')),
                ('num_bedrooms', models.IntegerField(verbose_name='تعداد خواب')),
                ('construction_year', models.CharField(max_length=4, verbose_name='تاریخ ساخت')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'آگهی',
                'verbose_name_plural': 'آگهی\u200cها',
            },
        ),
    ]
