# Generated by Django 5.1.4 on 2025-01-06 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='max_area',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='max_price',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='min_area',
            field=models.BigIntegerField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='min_price',
            field=models.BigIntegerField(),
        ),
    ]
