# Generated by Django 5.1.4 on 2025-01-05 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_request_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='created_at',
        ),
    ]
