# Generated by Django 5.1.4 on 2025-01-27 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0004_remove_request_user_remove_sellrequest_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_type', models.CharField(choices=[('purchase', 'خرید'), ('sale', 'فروش'), ('lease', 'رهن'), ('rent', 'اجاره')], max_length=50, verbose_name='نوع درخواست')),
                ('location', models.CharField(max_length=255, verbose_name='آدرس/شهر یا محله')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='متراژ')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='قیمت')),
                ('bedrooms', models.CharField(max_length=10, verbose_name='اتاق خواب')),
                ('facilities', models.TextField(blank=True, null=True, verbose_name='امکانات رفاهی')),
                ('message', models.TextField(verbose_name='پیام')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ارسال درخواست')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'درخواست مشاوره',
                'verbose_name_plural': 'درخواست\u200cهای مشاوره',
            },
        ),
    ]
