# Generated by Django 5.1.4 on 2025-01-27 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultationrequest',
            name='ad_type',
            field=models.CharField(choices=[('purchase', 'خرید')], max_length=50, verbose_name='نوع درخواست'),
        ),
    ]
