# Generated by Django 5.1.4 on 2025-01-05 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_request_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='request',
            name='max_area',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='max_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='min_area',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='request',
            name='min_price',
            field=models.IntegerField(),
        ),
    ]
