# Generated by Django 5.1.4 on 2025-01-24 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rentoutproperty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='user',
        ),
        migrations.RemoveField(
            model_name='sellrequest',
            name='user',
        ),
        migrations.DeleteModel(
            name='RentOutProperty',
        ),
        migrations.DeleteModel(
            name='Request',
        ),
        migrations.DeleteModel(
            name='SellRequest',
        ),
    ]
