# Generated by Django 5.1.4 on 2025-01-25 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='property_images/', verbose_name='تصویر')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('phone_number', models.CharField(max_length=11, unique=True, verbose_name='شماره تلفن')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='ایمیل')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('is_staff', models.BooleanField(default=False, verbose_name='کارمند')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='مدیر')),
                ('user_type', models.CharField(choices=[('normal', 'کاربر عادی'), ('agent', 'مشاور املاک'), ('agency', 'بنگاه املاک')], default='normal', max_length=10, verbose_name='نوع حساب')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام و نام خانوادگی')),
                ('agency_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='نام بنگاه')),
                ('whatsapp_number', models.CharField(blank=True, max_length=15, null=True, verbose_name='شماره واتساپ')),
                ('specialization', models.CharField(blank=True, max_length=255, null=True, verbose_name='تخصص مشاور')),
                ('activity_areas', models.JSONField(blank=True, null=True, verbose_name='محله\u200cهای حوزه فعالیت')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس کامل')),
                ('description', models.TextField(blank=True, null=True, verbose_name='توضیحات')),
                ('avatar', models.ImageField(default='/images/logo/images.png', upload_to='avatars/', verbose_name='آواتار')),
                ('profile_completed', models.BooleanField(default=False, verbose_name='پروفایل تکمیل شده')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان آگهی')),
                ('property_type', models.CharField(choices=[('apartment', 'آپارتمان'), ('villa', 'ویلا'), ('land', 'زمین'), ('house', 'خانه')], max_length=20, verbose_name='نوع ملک')),
                ('useproperty', models.CharField(choices=[('commercial', 'تجاری'), ('administrative', 'اداری'), ('residential', 'مسکونی')], max_length=20, verbose_name='کاربری ملک')),
                ('ad_type', models.CharField(choices=[('sale', 'فروش'), ('rent', 'رهن و اجاره'), ('purchase', 'خرید'), ('lease', 'اجاره')], max_length=20, verbose_name='نوع آگهی')),
                ('price_min', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='قیمت حداقل')),
                ('price_max', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='قیمت حداکثر')),
                ('deposit', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='پول پیش')),
                ('rent', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='اجاره ماهیانه')),
                ('city', models.CharField(max_length=50, verbose_name='شهر')),
                ('postalcode', models.CharField(max_length=10, verbose_name='کد پستی')),
                ('location', models.CharField(max_length=255, verbose_name='آدرس کامل')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='متراژ')),
                ('num_bedrooms', models.IntegerField(verbose_name='تعداد خواب')),
                ('construction_year', models.CharField(max_length=4, verbose_name='تاریخ ساخت')),
                ('description', models.TextField(verbose_name='توضیحات')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('images', models.ManyToManyField(blank=True, related_name='ad_properties', to='users.image')),
            ],
            options={
                'verbose_name': 'آگهی',
                'verbose_name_plural': 'آگهی\u200cها',
            },
        ),
    ]
