# Generated by Django 5.1.4 on 2025-01-25 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_property_delete_adproperty'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='status',
            field=models.CharField(choices=[('draft', 'پیش نویس'), ('published', 'منتشر شده'), ('expired', 'منقضی شده')], default='published', max_length=20, verbose_name='وضعیت آگهی'),
        ),
        migrations.AlterField(
            model_name='property',
            name='construction_year',
            field=models.CharField(max_length=10, verbose_name='تاریخ ساخت'),
        ),
    ]
